export const DO_NOTHING = 'DO_NOTHING';
export const START_SYNCING_COUNTER = 'START_SYNCING_COUNTER';
export const FINISH_SYNCING_COUNTER = 'FINISH_SYNCING_COUNTER';
export const SYNC_COUNTER = 'SYNC_COUNTER';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_BY = 'INCREMENT_BY';
export const DECREMENT_BY = 'DECREMENT_BY';
